#define QUALITY 2
// #define BLOOM 1 [0,1]
#if QUALITY >= 2
program.gbuffers_terrain.enabled=true
#else
program.gbuffers_terrain.enabled=false
#endif
program.final.enabled=false
program.composite.enabled=QUALITY >= 2 && !defined(DISABLED)
profile.high=QUALITY=3
profile.low=QUALITY=1
iris.features.required=LEGACY_GLSL,COMPOSITE
iris.features.optional=MRT
colortex0Format=RGBA16F
customImage0=ignored-by-m7_1
