package net.chimera.shaderpack;

/** Iris 1.10 WorldRenderingPhase: ordinals are part of the shader ABI. */
public enum PackRenderingPhase {
    NONE, SKY, SUNSET, CUSTOM_SKY, SUN, MOON, STARS, VOID,
    TERRAIN_SOLID, TERRAIN_CUTOUT_MIPPED, TERRAIN_CUTOUT,
    ENTITIES, BLOCK_ENTITIES, DESTROY, OUTLINE, DEBUG, HAND_SOLID,
    TERRAIN_TRANSLUCENT, TRIPWIRE, PARTICLES, CLOUDS, RAIN_SNOW,
    WORLD_BORDER, HAND_TRANSLUCENT
}
