# The feature is disabled by default and enabled only by an explicit
# -Dchimera.option.ENABLE_ADVANCED=1 override.
#if ENABLE_ADVANCED
image.test_image = test_sampler rgba rgba16f half_float true false 8 4 8
#endif
